version: 0.1.0.{build}
pull_requests:
  do_not_increment_build_number: true
configuration: Release
platform: Any CPU
before_build:
- cmd: nuget restore
build:
  project: StarMap.sln
  parallel: true
  verbosity: minimal
after_build:
- cmd: copy StarMap\bin\Release\StarMap.zip StarMap.zip
artifacts:
- path: StarMap.zip